### ISSUE TITLE
Need to edit EOSIO_ABI in deep.md

### ISSUE THREAD

**Issue by fan31415** [nsjames/Scatter-Tutorials#1]
There is no `setidx` function in the deep contract now, so 
```
EOSIO_ABI( platform, (setidx)(setacc)(getacc)(removeacc) )
```
should be replaced with
```
EOSIO_ABI( platform, (setapp)(setacc)(getacc)(removeacc) )
```

**Comment by nsjames** [comment]
Ah yup! Copy paste you failed me :)

10d18bb68a24419f28af63144c10f7e1ea1a0d05
