### ISSUE TITLE
Pure javascript examples for Scatter?

### ISSUE THREAD

**Issue by svenpohl** [nsjames/Scatter-Tutorials#3]
Are there some simple none node.js examples (pure javascript)? (I'm not familar with node.js!)
I cannot find any web3-like examples.

...and badly wish for Scatter:

1) Pure clientbased HTML/inline js "Hello World" demo, just showing the
current scatter - accountname
( like https://game.wizards.one/#/wizards ...showing the account )

2) Pure clientbases HTML/inline js "Transfer" demo, just a single button
opening scatter for a Transaction

All examples are based on node.js... but scatter works as embeded wallet
in crome, so it MUST be possible to access somewere with pure javascript, O 
guess. All what happens on the blockchain (f.e. incoming transactions on an
address) can be handled via PHP/Curl/BP-RPC-Entrypoints... 

Thank you!

**Comment by nsjames** [comment]
There's a new `scatter-js` library which can be dropped into standard html pages.

Check it out here: https://github.com/GetScatter/scatter-js

And there's an html testing page that shows some basic usage here: https://github.com/GetScatter/scatter-js/blob/master/index.html
